name: Fetch NSE CSV

on:
  schedule:
    - cron: '30 11 * * 1-5'  # Every weekday at 11:30 UTC (5:00 PM IST)
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch script
        run: python fetch_nse_price_bands.py

      - name: Remove old CSVs (keep only today)
        run: |
          today=$(date +"%d%m%Y")
          shopt -s extglob
          # Delete all CSV files NOT matching today's date pattern
          rm -f !(${today}.csv)

      - name: Commit and push CSVs if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Stage CSV files and deletions
          git add -A '*.csv'

          # Check if there are staged changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update NSE securities CSVs"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          fi
