name: Fetch NSE CSV

on:
  schedule:
    - cron: '31 13 * * 1-5' # Every weekday at 13:31 UTC (7:01 PM IST)
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-onname: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch script
        id: fetch
        run: python fetch_nse_price_bands.py

      - name: Remove old CSVs (keep only today)
        if: success()
        run: |
          today=$(date +"%d%m%Y")
          shopt -s nullglob
          found_csvs=false
          for file in [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].csv; do
            found_csvs=true
            if [[ -f "$file" && "$file" != "${today}.csv" ]]; then
              echo "Removing old CSV: $file"
              rm -f "$file"
            fi
          done
          shopt -u nullglob
          if [ "$found_csvs" = false ]; then
            echo "No CSV files found to delete. Skipping deletion step."
          fi

      - name: Commit changes
        if: success()
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.csv
          git add -u
          git diff-index --quiet HEAD || git commit -m "Update NSE securities CSVs"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force_with_lease: true
