name: Fetch NSE CSV

on:
  schedule:
    - cron: '30 11 * * 1-5'  # Every weekday at 11:30 UTC (5:00 PM IST)
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch script
        run: python fetch_nse_price_bands.py

      - name: Show files after fetch
        run: ls -la

      - name: Commit and push CSV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Files in current directory:"
          ls -la

          echo "Git status before adding files:"
          git status

          if ls *.csv 1> /dev/null 2>&1; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"

            git add *.csv

            echo "Git status after adding files:"
            git status

            git commit -m "Update NSE securities CSVs" || echo "No changes to commit"

            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "No CSV file to commit"
          fi
